# Generated by Django 4.1 on 2022-11-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppTwo", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Email",
            field=models.EmailField(max_length=264, unique=True),
        ),
    ]
